### ISSUE TITLE
Ajumamoro not starting from command line

### ISSUE THREAD

**Issue by delakanda** [ekowabaka/ajumamoro#1]
The queue is working and all with redis. But the issue now is starting the ajumamoro binary from the command line gives an error because even if you specify a broker in the command line:

vendor/bin/ajumamoro start -b=redis

it doesnt pick it up in the Broker code.. Broker is looking for the driver in  Config::get('ajumamoro:broker') || !Config::get('ajumamoro:broker.driver')

**Comment by ekowabaka** [comment]
Can I get the stack trace?

**Comment by delakanda** [comment]
dkanda@dkanda-pc:~/projects/TestApp$ vendor/bin/ajumamoro start -b=redis
[2016-11-13 04:03:38] [ajumamoro] INFO : Starting Ajumamoro
[2016-11-13 04:03:38] [ajumamoro] ERROR : Exception thrown [Exception] Please specify a broker for the jobs. on line 20 of /home/dkanda/projects/TestApp/vendor/ekowabaka/ajumamoro/src/Broker.php
[2016-11-13 04:03:38] [ajumamoro] DEBUG : Debug trace for exception #0 /home/dkanda/projects/TestApp/vendor/ekowabaka/ajumamoro/src/Broker.php(38): ajumamoro\Broker::factory() #1 /home/dkanda/projects/TestApp/vendor/ekowabaka/ajumamoro/src/Runner.php(113): ajumamoro\Broker::getInstance() #2 /home/dkanda/projects/TestApp/vendor/ekowabaka/ajumamoro/src/Runner.php(97): ajumamoro\Runner::getNextJob() #3 /home/dkanda/projects/TestApp/vendor/ekowabaka/ajumamoro/src/commands/Start.php(66): ajumamoro\Runner::mainLoop() #4 /home/dkanda/projects/TestApp/vendor/ekowabaka/clearice/src/ArgumentParser.php(231): ajumamoro\commands\Start->run(Array) #5 /home/dkanda/projects/TestApp/vendor/ekowabaka/clearice/src/ArgumentParser.php(210): clearice\ArgumentParser->executeCommand('start', Array) #6 /home/dkanda/projects/TestApp/vendor/ekowabaka/clearice/src/ClearIce.php(485): clearice\ArgumentParser->parse() #7 /home/dkanda/projects/TestApp/vendor/ekowabaka/ajumamoro/bin/ajumamoro(78): clearice\ClearIce::parse() #8 {main}

**Comment by ekowabaka** [comment]
Thanks! Some Markdown styling will help tho ;-)

**Comment by delakanda** [comment]
Lol yh markdown...next time
