### ISSUE TITLE
The Stop Command throws an Error

### ISSUE THREAD

**Issue by delakanda** [ekowabaka/ajumamoro#2]
Stopping the ajumamoro binary throws an error because there is a Configuration class missing in the ajumamoro project:

Stop.php

public function run($options)
    {
        ClearIce::output("Stopping ajumamoro daemon ... ");
        $options = Configuration::init($options); <- No Config classs
        $pidFile = Configuration::get('pid_file', './ajumamoro.pid');
        ...
}

**Comment by ekowabaka** [comment]
Can I get the stack trace?

**Comment by delakanda** [comment]
dkanda@dkanda-pc:~/projects/TestApp$ vendor/bin/ajumamoro stop
Stopping ajumamoro daemon ... PHP Fatal error:  Uncaught Error: Class 'ajumamoro\Configuration' not found in /home/dkanda/projects/TestApp/vendor/ekowabaka/ajumamoro/src/commands/Stop.php:13
Stack trace:
#0 /home/dkanda/projects/TestApp/vendor/ekowabaka/clearice/src/ArgumentParser.php(231): ajumamoro\commands\Stop->run(Array)
#1 /home/dkanda/projects/TestApp/vendor/ekowabaka/clearice/src/ArgumentParser.php(210): clearice\ArgumentParser->executeCommand('stop', Array)
#2 /home/dkanda/projects/TestApp/vendor/ekowabaka/clearice/src/ClearIce.php(485): clearice\ArgumentParser->parse()
#3 /home/dkanda/projects/TestApp/vendor/ekowabaka/ajumamoro/bin/ajumamoro(78): clearice\ClearIce::parse()
#4 {main}
  thrown in /home/dkanda/projects/TestApp/vendor/ekowabaka/ajumamoro/src/commands/Stop.php on line 13

Fatal error: Uncaught Error: Class 'ajumamoro\Configuration' not found in /home/dkanda/projects/TestApp/vendor/ekowabaka/ajumamoro/src/commands/Stop.php on line 13

Error: Class 'ajumamoro\Configuration' not found in /home/dkanda/projects/TestApp/vendor/ekowabaka/ajumamoro/src/commands/Stop.php on line 13

Call Stack:
    0.0003     375080   1. {main}() /home/dkanda/projects/TestApp/vendor/ekowabaka/ajumamoro/bin/ajumamoro:0
    0.0037     557088   2. clearice\ClearIce::parse() /home/dkanda/projects/TestApp/vendor/ekowabaka/ajumamoro/bin/ajumamoro:78
    0.0037     557088   3. clearice\ArgumentParser->parse() /home/dkanda/projects/TestApp/vendor/ekowabaka/clearice/src/ClearIce.php:485
    0.0044     578968   4. clearice\ArgumentParser->executeCommand() /home/dkanda/projects/TestApp/vendor/ekowabaka/clearice/src/ArgumentParser.php:210
    0.0047     586552   5. ajumamoro\commands\Stop->run() /home/dkanda/projects/TestApp/vendor/ekowabaka/clearice/src/ArgumentParser.php:231
